project_id = "fojnxsdgurparkpymekv"

[functions.analyze-inspiration]
verify_jwt = false

[functions.generate-jewelry-image]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
